### ISSUE TITLE
Traceback (most recent call last):   File "/workspaces/backpack-faskety-auto-trade/main.py", line 115, in <module>     begin_usdc_available = float(account_balance['USDC']['available']) KeyError: 'USDC'

### ISSUE THREAD

**Issue by GOODFLYO** [yuankongzhe/backpack-faskety-auto-trade#1]
Traceback (most recent call last):
  File "/workspaces/backpack-faskety-auto-trade/main.py", line 115, in <module>
    begin_usdc_available = float(account_balance['USDC']['available'])
KeyError: 'USDC'

**Comment by faskety** [comment]
已修复
